project:
  type: website

website:
  title: "Lucas Souza Santos"
  site-url: _quarto.yml
  description: "Blog pessoal"
  navbar:
    right:
      - href: about.qmd
        text: Sobre
      - icon: linkedin
        href: https://www.linkedin.com/in/lucas-souza-santos-709453165/
      - icon: github
        href: https://github.com/LUCAS-01SANTOS
      - icon: rss
        href: index.xml
execute:
  freeze: auto
format:
  html:
    theme: lux
    css: styles.css



